insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (1, 'Aquamarine', 'Bertrando', 'Blackish oystercatcher', 'Male', 3);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (2, 'Orange', 'Jonah', 'Black-crowned night heron', 'Male', 10);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (3, 'Indigo', 'Daile', 'Egyptian vulture', 'Female', 8);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (4, 'Fuscia', 'Kally', 'Egyptian vulture', 'Female', 4);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (5, 'Red', 'Cate', 'Barbet, crested', 'Female', 8);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (6, 'Mauv', 'Diego', 'Goose, greylag', 'Male', 6);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (7, 'Crimson', 'Buck', 'Duck, white-faced whistling', 'Male', 5);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (8, 'Turquoise', 'Franciskus', 'Bontebok', 'Male', 7);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (9, 'Violet', 'Missy', 'Desert spiny lizard', 'Female', 3);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (10, 'Maroon', 'Vic', 'Badger, eurasian', 'Male', 1);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (11, 'Orange', 'Michael', 'Vulture, white-headed', 'Male', 7);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (12, 'Khaki', 'Seth', 'Sulfur-crested cockatoo', 'Male', 2);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (13, 'Violet', 'Devin', 'Swamp deer', 'Male', 6);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (14, 'Khaki', 'Leighton', 'Otter, oriental short-clawed', 'Male', 2);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (15, 'Crimson', 'Sunny', 'Squirrel glider', 'Male', 4);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (16, 'Purple', 'Rad', 'Tortoise, burmese black mountain', 'Male', 2);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (17, 'Purple', 'Darcy', 'Hanuman langur', 'Male', 2);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (18, 'Blue', 'Kacie', 'Blue-tongued skink', 'Female', 7);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (19, 'Teal', 'Connie', 'Marten, american', 'Female', 6);
insert into MASCOTAENTITY (ID, COLOR, NAME, RAZA, SEXO, CLIENTE_ID) values (20, 'Teal', 'Elfrieda', 'Waterbuck, common', 'Female', 3);
